#page title
page_title                                :                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1600729989                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : it                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/discreet-black-screen-camera/id1600729989                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : More privacy in your hand

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marco Zabo                                
your_link                                 : https://uazoo.com                     
your_city                                 : Italy                                
email_address                             : uazooapps@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Black Screen Stealth Mode
    description                           : Activate a discreet black screen to ensure absolute privacy during camera use.
    fontawesome_icon_name                 : magic
    
  - title                                 : Covert Photo Capture
    description                           : Capture photos without any indicators or sounds to maintain confidentiality.
    fontawesome_icon_name                 : mobile

  - title                                 : Touch Gesture Activation
    description                           : Initiate recording or capture with customizable touch gestures, ensuring intuitive and quick operation experience
    fontawesome_icon_name                 : play-circle

  - title                                 : Private Gallery
    description                           : Store captured photos and videos in a secure gallery with additional FaceID protection for added privacy.
    fontawesome_icon_name                 : sync

  - title                                 : Encrypted File Storage
    description                           : Ensure the security of your recorded content with encrypted file storage to prevent unauthorized access.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Share and Save
    description                           : Save your pictures to camera roll or share
    fontawesome_icon_name                 : star

  - title                                 : 4K Videos
    description                           : Enjoy 4K videos @ 60 FPS.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Themes and Categories
    description                           : Browse through themed categories, such as animals, mandalas, landscapes, and more, to find the perfect coloring page for your mood.
    fontawesome_icon_name                 : link



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/head.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
